### ISSUE TITLE
trouble with peripheral disconnect

### ISSUE THREAD

**Issue by gmas** [bbx10/node-nRF8001#4]
Hi there and thank you for writing this, I've been having fun with it !

I have a long-running process where I set discoverAll to run on a 30s interval, set a timeout to do stopDiscoverAll after 10s, connect to a peripheral and then disconnect after receiving some data.

```
var nrfuart = require('nrfuart');                                           

function onDiscover(ble_uart) {                                             
  ble_uart.connectAndSetup(function() {                                     
    ble_uart.on('data', function(data) {                                    
      console.log("data: ", data.toString());
      ble_uart.disconnect(); 
    });
    ble_uart.write('GET');
  });
}

//discover every 30s
setInterval(function() {
  nrfuart.discoverAll(onDiscover);
  //stop discovery after 10s
  setTimeout(function() {
    nrfuart.stopDiscoverAll(onDiscover);
  }, 10000);
}, 30000);

```

The problem is that after 10 loops I get a warning about a possible memory coming from having 11 disconnect listeners added.

```
(node) warning: possible EventEmitter memory leak detected. 11 disconnect listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Peripheral.addListener (events.js:179:15)
    at NobleDevice (/home/gmas/play/ble/node_modules/nrfuart/node_modules/noble-device/lib/noble-device.js:14:20)
    at new nrfuart (/home/gmas/play/ble/node_modules/nrfuart/index.js:40:17)
    at Noble.constructor.onDiscover (/home/gmas/play/ble/node_modules/nrfuart/node_modules/noble-device/lib/util.js:28:22)
    at Noble.emit (events.js:107:17)
    at Noble.onDiscover (/home/gmas/play/ble/node_modules/nrfuart/node_modules/noble-device/node_modules/noble/lib/noble.js:125:10)
    at emit (events.js:118:17)
    at nobleBindings.onDiscover (/home/gmas/play/ble/node_modules/nrfuart/node_modules/noble-device/node_modules/noble/lib/linux/bindings.js:74:10)
    at emit (events.js:118:17)
    at HciBle.onStdoutData (/home/gmas/play/ble/node_modules/nrfuart/node_modules/noble-device/node_modules/noble/lib/linux/hci-ble.js:174:14)
```

Is my approach wrong or am I missing something simple? 

Thanks

**Comment by simar88** [comment]
Any news about this issue? Thanks in advance. :)
